export const FETCH_ALL_USER = "FETCH_ALL_USER";
export const FETCH_ALL_ADS = "FETCH_ALL_ADS";

export const FETCH_TOTAL_USERS = "FETCH_TOTAL_USERS";
export const FETCH_TOTAL_TEMP_USERS = "FETCH_TOTAL_TEMP_USERS";
export const FETCH_TOTAL_PERM_USERS = "FETCH_TOTAL_PERM_USERS";
export const FETCH_TOTAL_ACTIVE_USERS = "FETCH_TOTAL_ACTIVE_USERS";


export const FETCH_TOTAL_ADS = "FETCH_TOTAL_ADS";
export const FETCH_TOTAL_TEMP_ADS = "FETCH_TOTAL_TEMP_ADS";
export const FETCH_TOTAL_PERM_ADS = "FETCH_TOTAL_PERM_ADS";
export const FETCH_TOTAL_ACTIVE_ADS = "FETCH_TOTAL_ACTIVE_ADS";
export const ISLOGIN_ADMIN = "ISLOGIN_ADMIN";
export const ISLOGOUT_ADMIN = "ISLOGOUT_ADMIN";



